### ISSUE TITLE
Rating Scale (pretty sure this is a bug).

### ISSUE THREAD

**Issue by Testydudey** [RoVSRG/robeats-cs#11]
When using the rate buttons on a map, in the results screen the "Difficulty" of the song scales with the rate the map that is being played at (shows the "true" rating of the map).
Example: ![YumaFD1 45](https://user-images.githubusercontent.com/84602288/119739698-3a4d4f80-be48-11eb-8a16-54d507ccdf05.PNG)

**Comment by thenerdie** [comment]
Are you saying that the "scaled" difficulties are inaccurate? If so, this is a known issue. Improvements to the rating scale will come in the future. For now, take that value with a grain of salt.

**Comment by Testydudey** [comment]
> Are you saying that the "scaled" difficulties are inaccurate? If so, this is a known issue. Improvements to the rating scale will come in the future. For now, take that value with a grain of salt.

No, I am saying that it shows the ACTUAL difficulty of the map on the specific rate (future dominators is a 42 on 1.0 and in this case is rounded to a 53 on 1.45 and actually shown as a 53). I didn't know if this was 100% a bug or not as this wasn't a feature in legacy RCS, it would just show "42 1.27x" or something like that. If this is not a bug then I'm sorry :/

**Comment by thenerdie** [comment]
Ah, this isn't a bug. This is intentional behavior! Thanks for filing an issue, though.
