### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by arceuss** [RoVSRG/robeats-cs#25]
just gives me 
[ERROR rojo] Rojo project referred to a file using $path that could not be turned into a Roblox Instance by Rojo.
        Check that the file exists and is a file type known by Rojo.
        Project path: C:\Users\arceus\Desktop\burger\robeats-cs\default.project.json
        File $path: Packages

**Comment by thenerdie** [comment]
Have you set up Wally? Wally is a package manager we use to manage our external dependencies. Download [this](https://github.com/UpliftGames/wally) and add the binary to your PATH. After this, run `wally install` in the project directory and you should be able to build.

**Comment by arceuss** [comment]
works now thank you
