### ISSUE TITLE
ReplicatedStorage/Skins/whatsappcarreal.rbxmx is malformed

### ISSUE THREAD

**Issue by p0s0** [RoVSRG/robeats-cs#30]
I noticed this whilst trying to build. The XML gets cut off at the end.
![image](https://user-images.githubusercontent.com/73150246/214080549-750755d2-c957-414e-a06a-d44fd8248b4a.png)

**Comment by yasicreeper** [comment]
Thanks for the message, ill update the code in a minute :)

**Comment by yasicreeper** [comment]
updated it thanks again

**Comment by p0s0** [comment]
fixed
