### ISSUE TITLE
Yellow Circle That Flashes In Middle Of Track During Gameplay

### ISSUE THREAD

**Issue by ChickenHumanPerson** [RoVSRG/robeats-cs#8]
This Yellow Circle In The Middle Is Bothering Me Alot During Playing.

https://user-images.githubusercontent.com/53623885/119200795-a3ede800-ba5b-11eb-8bf4-43d2351f93a0.mp4
 
If There Is A Way To Get Rid Of It, Please Do.

**Comment by thenerdie** [comment]
For now, turn base transparency to 0 in settings. This is a known issue, thanks for filing an issue. :D

**Comment by ChickenHumanPerson** [comment]
Alright.

**Comment by astralkingdummy** [comment]
all i know is that the yellow circle is at the origin point
